spring.application.name=sistema

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/imber_db
spring.datasource.username=root
spring.datasource.password=escola
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=109342123588-thp38rr2dc1f6v7mb1tmidbc56klqsbh.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=SEU_CLIENT_SECRET_AQUI
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/calendar.events
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google

# Google OAuth2 Configuration for Calendar
google.oauth2.client-id=${spring.security.oauth2.client.registration.google.client-id}
google.oauth2.client-secret=${spring.security.oauth2.client.registration.google.client-secret}